config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'posts#index'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/kuchikomi.rb
class Kuchikomi < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy

    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :liked_posts, through: :likes, source: :post
         has_many :comments, dependent: :destroy
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 }
         mount_uploader :image, ImageUploader
         
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.build(comment_params) 
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) 
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) 
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id])
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

    def index
      if params[:search] == nil
        @posts= Post.all
      elsif params[:search] == ''
        @posts= Post.all
      else
        @posts = Post.where("about LIKE ? ",'%' + params[:search] + '%')
      end
    end

    def new
        @post = Post.new
      end
    
      def create
        post = Post.new(posts_params)
        post.user_id = current_user.id
        if post.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @post = Post.find(params[:id])
        @comments = @post.comments
        @comment = Comment.new
      end

      def edit
        @post = Post.find(params[:id])
      end

      def update
        post = Post.find(params[:id])
        if post.update(posts_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
      end
    
      private
      def posts_params
        params.require(:post).permit(:name, :about, :image)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/kuchikomi_helper.rb
module KuchikomiHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Bench</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/e0a3ec5935.js" crossorigin="anonymous"></script>

  </head>
  <body>
  <header>
   <h1>Bench</h1>
   
   <div class="header-list">
    <ul>
    <li><%= link_to "Top page", posts_path %></li>
    <li><%= link_to "投稿", new_post_path %></li>
    <% if user_signed_in? %>
    <li><%= link_to "マイページ", user_path(current_user.id) %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
   <% else %>
    <li><%= link_to "新規登録", new_user_registration_path %></li>
    <li><%= link_to "ログイン", new_user_session_path %></li>
   <% end %>
    </ul>
   </div>
  </header>
  <main>
   <%= yield %>
  </main>
  
  <footer>
      <p>©仮決めフッター.</p>
  </footer>

 </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %> 

    <div class="field">
    <%= f.label :about %>
    <%= f.text_field :about, :size => 140 %>
    </div>

    <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
    <%= f.submit "編集する" %>
  <% end %>
  

app/views/posts/index.html.erb
<div class="background">   #1
<h1>Bench</h1>
<link rel="stylesheet" href="index.css">

<h3>投稿を検索</h3>
 <div class="search"> #2
 <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
 </div>#2

<%= button_to "新規投稿へ", new_post_path %>

<div class="posts-container">#3
<h4>投稿一覧</h4>
  <% @posts.each do |t| %>
  <div class="post">#4
<div class="p">#5
  <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
  <figure class="image"><%= image_tag t.image_url, size: "250x200" if t.image? %></figure>
  <div class="text">#6
  <%= link_to t.user.name, user_path(t.user.id) %>  
  <%= t.user.email %> 
    <%= t.name %>
    <%= t.about %>
    <%= t.image %>
  </div>#6
</div>#4か5のどれか

    <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
            <i class="fa-solid fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
            <i class="fa-solid fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="fa-solid fa-heart"></i><%= t.likes.count %>
  <% end %>

    <%= link_to "詳細へ", post_path(t.id) %> 
    <%= link_to "編集する", edit_post_path(t.id) %>
    <%= button_to "削除する", post_path(t.id), method: :delete %>
  </div>#4
  <% end %>
</div>#3
</div>#1

app/views/posts/new.html.erb
<link rel="stylesheet" href="new.css">
<h1>新規投稿ページ</h1>
<h3>新規投稿</h3>
<%= form_for @post do |f| %>

<div class="post-container">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :about %>
    <%= f.text_field :about, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :image %>
  </div>
    <div class="image">
    <%= f.file_field :image %>
    </div>


  <%= f.submit "投稿する" %>
<% end %>
</div>
<%= link_to "一覧に戻る", posts_path %>

app/views/posts/show.html.erb
<h1>Benchtime</h1>
<h3>投稿詳細</h3>
<div class="post">
  <p><%= @post.name %></p>
  <p><%= @post.about %></p>
  <p><%= @post.image %></p>
  <p><%= @post.created_at %></p>

    <% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
        <%= button_to post_like_path(@post), method: :delete do %>
          <i class="fas fa-heart"></i><%= @post.likes.count %>
        <% end %>
      <% else %>
        <%= button_to post_likes_path(@post), method: :post do %>
          <i class="far fa-heart"></i><%= @post.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @post.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_post_path(@post.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
</div>

<div class="kuchikomi-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-kuchikmomi"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "投稿一覧に戻る", posts_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<%= image_tag @user.image_url, size: "250x200" if @user.image? %>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.about %>
  <%= t.image %>
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_posts.each do |t| %>
  <%= t.user.name %>
  <%= t.about %>
  <%= t.image %>
<% end %>

<%= link_to "投稿一覧に戻る", posts_path %>